---
- hosts: all
  gather_facts: no

  pre_tasks:
  - set_fact:
      is_become:
        "{% if ansible_ssh_user == 'root' %}no{% else %}yes{% endif %}"

  roles:
  - { role: hostname, when: hostname is defined }
  - { role: user, when: user_list is defined }
  - ssh
  - { role: network, when: network_list is defined }
  - role: firewall
    when: service_list is defined or port_list is defined
  - locale
  - update