---
- name: setting sshd_config
  become: "{{ is_become }}"
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
  - regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  - regexp: '^(#\s*)?PasswordAuthentication '
    line: 'PasswordAuthentication no'
  notify: restart sshd service