---
- name: setting sshd_config
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  notify: restart sshd service
  loop:
  - regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  - regexp: '^(#\s*)?PasswordAuthentication '
    line: 'PasswordAuthentication no'