---
- name: install needed network manager libs
  dnf:
    name:
      - NetworkManager-libnm
      - python3-libsemanage
      - python3-policycoreutils
    state: present

- name: setup network
  nmcli:
    conn_name: "{{ item.conn_name }}"
    ifname: "{{ item.ifname }}"
    type: ethernet
    ip4: "{{ item.ip4 }}"
    autoconnect: "{{ item.autoconnect }}"
    state: present
  loop: "{{ network_list }}"